In [1]:
!pip install econ_jp

Collecting econ_jp
  Downloading econ_jp-0.1.1-py3-none-any.whl (3.9 kB)
Installing collected packages: econ-jp
Successfully installed econ-jp-0.1.1

In [15]:
from econ_jp import econ_jp
import pandas as pd
import plotly.express as px

In [4]:
dir(econ_jp)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'boj_monetary_base',
 'boueki_total_monthly',
 'kakei_chosa',
 'np',
 'pd']

In [8]:
kakei_chosa = econ_jp.kakei_chosa()
kakei_chosa.head()

                             2000-01-31  2000-02-29  2000-03-31  2000-04-30  \
階層 大分類 中分類 小分類 品目分類
-  -   -   -   世帯数分布(抽出率調整)    10000.00    10000.00    10000.00    10000.00
               集計世帯数            7887.00     7942.00     7934.00     7922.00
               世帯人員(人)             3.32        3.32        3.32        3.32
               18歳未満人員(人)          0.74        0.75        0.75        0.75
               65歳以上人員(人)          0.52        0.53        0.53        0.52

                             2000-05-31  2000-06-30  2000-07-31  2000-08-31  \
階層 大分類 中分類 小分類 品目分類
-  -   -   -   世帯数分布(抽出率調整)    10000.00    10000.00    10000.00    10000.00
               集計世帯数            7928.00     7917.00     7907.00     7908.00
               世帯人員(人)             3.31        3.31        3.31        3.31
               18歳未満人員(人)          0.75        0.74        0.74        0.74
               65歳以上人員(人)          0.52        0.53        0.54        0.53

                             2000-09-30  2000-10-31  ...  2021-06-30  \
階層 大分類 中分類 小分類 品目分類                                  ...
-  -   -   -   世帯数分布(抽出率調整)    10000.00    10000.00  ...    10000.00
               集計世帯数            7917.00     7937.00  ...     7401.00
               世帯人員(人)             3.31        3.30  ...        2.93
               18歳未満人員(人)          0.74        0.73  ...        0.54
               65歳以上人員(人)          0.53        0.54  ...        0.85

                             2021-07-31  2021-08-31  2021-09-30  2021-10-31  \
階層 大分類 中分類 小分類 品目分類
-  -   -   -   世帯数分布(抽出率調整)    10000.00    10000.00    10000.00    10000.00
               集計世帯数            7370.00     7397.00     7378.00     7407.00
               世帯人員(人)             2.93        2.93        2.93        2.93
               18歳未満人員(人)          0.55        0.55        0.56        0.56
               65歳以上人員(人)          0.85        0.85        0.83        0.84

                             2021-11-30  2021-12-31  2022-01-31  2022-02-28  \
階層 大分類 中分類 小分類 品目分類
-  -   -   -   世帯数分布(抽出率調整)    10000.00    10000.00    10000.00    10000.00
               集計世帯数            7411.00     7416.00     7353.00     7315.00
               世帯人員(人)             2.93        2.92        2.92        2.92
               18歳未満人員(人)          0.55        0.55        0.55        0.55
               65歳以上人員(人)          0.84        0.85        0.84        0.85

                             2022-03-31
階層 大分類 中分類 小分類 品目分類
-  -   -   -   世帯数分布(抽出率調整)    10000.00
               集計世帯数            7369.00
               世帯人員(人)             2.92
               18歳未満人員(人)          0.54
               65歳以上人員(人)          0.84

[5 rows x 267 columns]

In [11]:
single_kakei = econ_jp.kakei_chosa(multi_index=False)
single_kakei.head()

,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,2000-10-31,...,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31
世帯数分布(抽出率調整),10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,...,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00
集計世帯数,7887.00,7942.00,7934.00,7922.00,7928.00,7917.00,7907.00,7908.00,7917.00,7937.00,...,7401.00,7370.00,7397.00,7378.00,7407.00,7411.00,7416.00,7353.00,7315.00,7369.00
世帯人員(人),3.32,3.32,3.32,3.32,3.31,3.31,3.31,3.31,3.31,3.30,...,2.93,2.93,2.93,2.93,2.93,2.93,2.92,2.92,2.92,2.92
18歳未満人員(人),0.74,0.75,0.75,0.75,0.75,0.74,0.74,0.74,0.74,0.73,...,0.54,0.55,0.55,0.56,0.56,0.55,0.55,0.55,0.55,0.54
65歳以上人員(人),0.52,0.53,0.53,0.52,0.52,0.53,0.54,0.53,0.53,0.54,...,0.85,0.85,0.85,0.83,0.84,0.84,0.85,0.84,0.85,0.84

In [12]:
boueki = econ_jp.boueki_total_monthly()
boueki.head()

             exp_total   imp_total  trade_balance
date
1979-01-01  1192541404  1476341312     -283799908
1979-02-01  1547063623  1474768659       72294964
1979-03-01  1924706473  1729013255      195693218
1979-04-01  1674210856  1754000207      -79789351
1979-05-01  1795127553  1971518433     -176390880

In [13]:
mb = econ_jp.boj_monetary_base()
mb

           マネタリーベース 日本銀行券発行高  貨幣流通高   日銀当座預金 日銀当座預金（準備預金） マネタリーベース（季節調整済み）
日付
1970-01-31    45652    39944   2830      NaN         2878            43342
1970-02-28    42889    36741   2769      NaN         3379            43916
1970-03-31    44223    38554   2794      NaN         2875            44822
1970-04-30    44354    38362   2846      NaN         3146            45139
1970-05-31    43996    37895   2887      NaN         3214            45569
...             ...      ...    ...      ...          ...              ...
2021-12-31  6570831  1195994  50634  5324203      4723644          6624768
2022-01-31  6627169  1200882  50522  5375765      4766767          6688543
2022-02-28  6571737  1189069  50252  5332416      4708623          6704859
2022-03-31  6621323  1195622  49977  5375724      4722652          6781184
2022-04-30  6874736  1200400  49711  5624625      4950597          6830731

[628 rows x 6 columns]

In [14]:
mb.to_csv('mb.csv')

In [18]:
df = pd.read_csv('mb.csv', index_col=0)
fig = px.line(mb, x=mb.index, y='マネタリーベース', title='マネタリーベース')
fig.show()

In [19]:
with open('fig1.html', 'a') as f:
    f.write(fig.to_html(full_html=False, include_plotlyjs='cdn'))